# Copyright 2026 The OpenFst Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# See https://github.com/actions/runner-images.

name: "Bazel (x64 Linux)"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
    build-and-test-x64-linux-bazel:
      name: Build and Test
      runs-on: ubuntu-latest
      env:
        USE_BAZEL_VERSION: 9.0.0
      steps:
        - uses: actions/checkout@v6
        - name: Setup Bazel
          uses: bazel-contrib/setup-bazel@0.18.0
          with:
            # Avoid downloading Bazel every time.
            bazelisk-cache: true
            # Store build cache per workflow.
            disk-cache: ${{github.workflow}}
            # Share repository cache between workflows.
            repository-cache: true
        - name: Check Bazelisk
          run: bazelisk --version
        - name: Build
          run: |
            bazelisk build --config=dev -c fastbuild //...
        - name: Test
          run: >-
            bazelisk test --config=dev -c fastbuild
            --test_size_filters=-enormous --test_output=errors
            //...
